### ISSUE TITLE
You're breaking the public API too often.

### ISSUE THREAD

**Issue by peterbourgon** [opentracing/opentracing-go#100]
About every week, I or one of my contributors has to submit a (sometimes large) patch to Go kit to get our continuous integration working again, after OpenTracing changes its public API. [Here](https://circleci.com/gh/go-kit/kit/911) is the most recent example I noticed today. Can you please make an effort to reduce the number of breaking changes you make to exported types and method sets? Thank you!

**Comment by bensigelman** [comment]
@peterbourgon FWIW, on May 2 [you wrote](https://github.com/go-kit/kit/pull/247#issuecomment-216176719):

```
... And for the record Go kit has no problem with API breakage; all of our consumers are vendoring.
```

I had remembered the above and kept it in mind as a consideration... since we're about to add direct dependencies from (gRPC)[https://github.com/grpc-ecosystem/grpc-opentracing], I wanted to make any planned breaking changes ASAP.

The consolation here is that there are only a few more issues before we declare OT 1.0 and make backwards-compatibility more of a priority: https://github.com/opentracing/opentracing.github.io/milestone/2

Of those, only https://github.com/opentracing/opentracing.github.io/issues/106 will introduce breaking changes (though that one will not affect go-kit since it doesn't use `Baggage`). The [KV logging](https://github.com/opentracing/opentracing.github.io/issues/96) will deprecate the older logging methods, but I don't think we'll remove them just yet.

In any case, as an olive branch I will make sure to prepare go-kit PRs in tandem with any remaining breaking OT-go changes. I think we're mostly out of the woods, though.

Sorry for the trouble.

**Comment by peterbourgon** [comment]
Yep, in retrospect this came across a little strong, which I apologize for. In the end breaking changes are just annoying to me :) so it's not a terrible thing, no users are complaining or anything. Just wanted to provide a bit of signal that it _is_ being noticed. Take whatever action you deem appropriate. And thanks again for the great work!

**Comment by bensigelman** [comment]
@peterbourgon absolutely no reason to apologize -- breaking changes are incredibly annoying. I reiterate my offer to help with any breaking in go-kit resulting from OT-go changes (though admittedly I don't anticipate any :)
