### ISSUE TITLE
Noop-specific errors

### ISSUE THREAD

**Issue by djspoons** [opentracing/opentracing-go#111]
Currently the NoopTracer returns ErrSpanContextNotFound from Extract, which makes it seem like the caller's fault, when in fact, Extract will never succeed. Could we use a different error, e.g. `ErrNotImplemented` or something else to tell the user that they shouldn't expect this to succeed with the default tracer?

**Comment by yurishkuro** [comment]
`ErrSpanContextNotFound` is not an indication of the caller's fault, but a lack of tracing context in the incoming request. I would rather not add "not implemented", it only requires more logic in the instrumentation.

**Comment by djspoons** [comment]
We had a customer that provided valid context, but of course it wasn't valid for the NoopTracer, just for our tracer. Since he was trying to debug a custom carrier, he assumed that it was his problem, and it took him+me a while to figure out that he was just using the wrong tracer.

Maybe ErrInvalidSpanContext is a better choice than ErrSpanContextNotFound? (Since in this case the context was created by a different tracer.)

**Comment by yurishkuro** [comment]
From the point of view of NoopTracer there was no context in that request, since it could never inject any in the first place.

I've done a lot of instrumentations and usually rely on the error code to mean something. If tracer returns `ErrInvalidSpanContext`, I usually log this error because it often indicates a misconfiguration / programmer's error. But I don't log `ErrSpanContextNotFound` since it's "business as usual". So if an application is running some instrumented RPC frameworks that logs this error, and if it happens to run with NoopTracer it will be logging errors on every request if the tracer returns `ErrInvalidSpanContext`.

I realize I am not offering an alternative solution, but I don't think changing `ErrSpanContextNotFound` is a good approach. Noop tracer is a special case, but it's current behavior is consistent with how the errors are defined.

**Comment by djspoons** [comment]
Ok. I think I get why this isn't going to work. Thanks
