### ISSUE TITLE
Rename SpanContext

### ISSUE THREAD

**Issue by rakyll** [opentracing/opentracing-go#124]
SpanContext is named after context.Context. The name is preserved to the implementations of contexts whereas SpanContext is an arbitrary interface that doesn't implement context.Context. SpanHandle or SpanValues could have been better names for this particular type.

**Comment by yurishkuro** [comment]
> SpanContext is named after context.Context

That's not accurate. SpanContext is language-neutral concept in OpenTracing. And it plays a different role; SpanContext is used for inter-process propagation, context.Context is used for in-process propagation.

You can think of it this way: there is an abstract concept called "distributed context", which is the fundamental substrate on which distributed tracing exists. Distributed context must be propagated both in-process and between processes. One of the data element in that context is tracing data. In-process that data is Span, because we want not just propagate it but also write to it. Inter-process that data is SpanContext, an immutable representation of the tracing context.

**Comment by yurishkuro** [comment]
closing old issue
