### ISSUE TITLE
Don't export NoopTracer or move

### ISSUE THREAD

**Issue by rakyll** [opentracing/opentracing-go#125]
If no Tracers have been set, the package can work against the unexpected noopTracer. If a no-op tracer is required for testing or similar, it could be exported from a testing package.

NoopTracer is adding noise to the initial API surface while not being significantly useful.

**Comment by yurishkuro** [comment]
Does this clarify why it's needed?

https://github.com/opentracing/opentracing-go/pull/128

**Comment by rakyll** [comment]
Thanks, this looks more clarifying but is this different than setting the global tracer to nil?

The solution might just be documenting that the client will do nothing if global tracer is set to nil and s/NoopTracer/noopTracer.

**Comment by yurishkuro** [comment]
I think NoopTrace is relevant even without "global" tracer. "global" singletons are bad anyway, so you'd rather build your RPC framework to allow the tracer to be injected. But what if it's not injected? Maybe the end user isn't interested in tracing. Then, unless you want to keep checking for nil everywhere, you need a no-op implementation. That's why this class is public.

**Comment by rakyll** [comment]
Ah, ok. Sounds good.

**Comment by yurishkuro** [comment]
Fixed by #128
