### ISSUE TITLE
Support for binary plugins?

### ISSUE THREAD

**Issue by tomwilkie** [opentracing/opentracing-go#133]
Has anyone given any thought to / already implemented using go1.8's binary plugins* to add a tracer implementation at runtime?  Would be nice to be able to specify the tracer to use as a command line flag and have opentracing load it...  WDYT?

* https://tip.golang.org/doc/go1.8#plugin

**Comment by yurishkuro** [comment]
I think it would be useful for people who ship binaries and have to compile them against different tracers today. A plugin would export a factory function for the Tracer. The difficult part is defining a common configuration mechanism and agreeing on the factory function signature (e.g. Jaeger tracer factory returns `io.Closer` as one of the return values).

I would rather see some larger projects start using plugins and work out the configuration story first. But if you have concrete suggestions, happy to discuss.

**Comment by tomwilkie** [comment]
> But if you have concrete suggestions, happy to discuss.

Nothing concrete, just thought it might be a good use of plugins.  They are a bit new right now, so yeah, letting others figure out any teething issues sounds sensible.

**Comment by bensigelman** [comment]
@tomwilkie I was just thinking about this for whatever reason... it'd be interesting to make some form of post-build-time Tracer binding a part of the OT Spec v2.0. Kind of like the ServiceLoader stuff in https://github.com/opentracing-contrib/java-globaltracer.

**Comment by yurishkuro** [comment]
@bensigelman I think the simplest way is to define a factory function `func() opentracing.Tracer` that can be retrieved from the plugin. Agreeing on a more general solution is a big more complicated, because initialization of the tracer is a very custom thing, especially when it comes to configuration. For example, these are the fairly common concerns of the initialization:
  * providing a service name to the tracer
  * init function returning an error
  * a way to do a clean shutdown of the tracer, forcing a flush of all in-memory spans (e.g. init function returning `io.Closer`)
  * providing custom configuration to the tracer

The last part is practically impossible to standardize on, and per [12-Factor App](https://12factor.net/) should probably be left to environment variables. Which makes the factory function
```go
type TracerFactory func(appName string) (opentracing.Tracer, io.Closer, error)
```

**Comment by bensigelman** [comment]
I was imagining that all tracer config in this scenario would be done through environment variables, yeah.

I wouldn't have expected an `io.Closer`, though... we already force people to cast (or at least know the type of) their Tracer if they want graceful shutdown, after all. Maybe there could just be a convention / suggestion that Tracers implement `io.Closer` for graceful shutdown? A conditional cast would work in that case.

**Comment by yurishkuro** [comment]
`io.Closer` by convention sounds fine to me. But today casting is not required, because when people init the tracer manually they already can get a concrete implementation.

**Comment by yurishkuro** [comment]
This plugin functionality can be implemented as a standalone library, so doesn't need to be in the API repository. Also, i've seen Go plugins not recommended on several occasions by Go developers (https://github.com/census-instrumentation/opencensus-service/pull/70#issuecomment-427990304).
