### ISSUE TITLE
TraceID/SpanID is injected, if if the span is not sampled.

### ISSUE THREAD

**Issue by tcolgate** [opentracing/opentracing-go#189]
## Use Case

Propagating spans from a loadbalacner with a sample rate of 1/100 to downstream applications with their own sampling.

## Problem

OpenTracnig Go injects a traceid/apanid into downstream requests, even if the sampling has selected this span and emitted a root span (in the case where the there was no span extracted from the inbound request).

Because downstream gets a Trace/Span it probably should use it (regardless of sampling flag?), but this means that if it decides to sample it will publish spans where no root span exists in the cetnralized storage.

Is this behaviour intended?

**Comment by yurishkuro** [comment]
Yes. Since OpenTracing only defines forward propagation for context, it doesn't really matter where the sampling happens - whenever it does, that span becomes the root span. I am not immediately aware of any implementation that do such opportunistic sampling at lower levels, but (a) it's not difficult to implement (although it skews the extrapolation stats, which is why we didn't do it in Jaeger), and (b) it can easily be written to throw away the reference to the unsampled parent span so that from the collected trace you won't even be able to tell that the root span is actually someone's child span.

**Comment by tcolgate** [comment]
Great, that makes sense.
Sorry if this was off topic, the thing doing the non sampled propagation is an opentracing-go app (traefik), and I suspected a bug here. 
  This has been useful though. Sorry to waste your time.
  Opentracing-go, and Jaeger are fantastic tools. I'm struggling integrating OpenCensus at the moment and the experience has been considerably more frustrating.
  Thanks for your work here, it's much appreciated.

**Comment by yurishkuro** [comment]
No worries, you're welcome. I cannot provide much insight into OpenCensus inner workings. I do recall them mentioning that they can upsample in the middle of unsampled trace, based on the latency profile of the portion of the current trace inside a given process. I don't know how valuable that feature is, and it certainly raises a lot of other questions.
