### ISSUE TITLE
Rethink package stucture

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-go#4]
Something like this:
```
/ README, LICENSE
/ Makefile, CI files (.travis.xml or whatever)
/ opentracing / - construction API only, and globals, utils
/ opentracing / raw / - reporter and context source
/ opentracing / std / - standard tracer impl of construction API
/ examples /
/ examples / dapperish / - sample implementation
/ examples / ping-pong / - simple client/server pair illustrating the usage of tracing API w/ dapperish
```

**Comment by bensigelman** [comment]
I'll send out a PR with parts of this... Go sometimes annoys me with stuff like this: I end up wanting the last segment of every path name to be meaningful, as programmers end up using it to qualify symbols. E.g., I would do `standardtracer` instead of `std` just so that programmers would end up writing `standardtracer.New`. And so on.

**Comment by bensigelman** [comment]
(still need to deal with README/LICENSE/etc, as well as think about `opentracing/raw`)

**Comment by yurishkuro** [comment]
@bensigelman as I am working through Python version, I've ran into a couple of issues with the packages and inheritance.

1. The main `opentracing` package has no need for Raw API. I think we've settled on the binding and instrumentation to be done at the `Tracer` level, so the Raw API becomes implementation detail of `standardtracer` package. Should we move it there? 

2. The RawSpan has certain efficiency gains in Go because it's embedded by value into the standard span. However, in Python it seems redundant, as it just introduces an unnecessary indirection for storing and reading the values.  I am thinking of merging it into standard span - any thoughts?

3. The main Tracer embeds Trace Context Source interface. This seems unnecessary, as it leaks the `NewRootTraceContext()` method into the Tracer interface.  What Tracer really needs is the two marshaler interfaces, but not the actual Source. There is some magic going on in the Go version where standardTracer manages to expose Source's methods directly by embedding it, but in Python that doesn't work, the tracer would have to re-implement the marshal methods and delegate to the Source implementation.

**Comment by yurishkuro** [comment]
One more suggestion (as long as we're discussing the structure) - I would like to move `NewChild` method from `TraceContext` to `TraceContextSource`. The Source already has `NewRootTraceContext()` method, and I think it's better to keep context creation methods in a single interface, where they can share random number generator and the knowledge of how context ID is structured.

**Comment by bensigelman** [comment]
@yurishkuro thanks for the thoughts/suggestions...

1) [Recorder.RecordSpan](https://github.com/opentracing/api-golang/blob/master/opentracing/recorder.go#L25) accepts a `RawSpan`, so I don't think the raw API qualifies as an implementation detail (for better or worse)
1) I like the idea of an immutable `RawSpan` interface for a span that's been finished. To my mind it makes the API boundaries clearer (that you can only record something once it's done, for instance). It's also a narrower interface for any recording machinery to interact with (in case span *creation* and span recording end up being satisfied by fundamentally different libraries... kind of like how [`StandardTracer.New`](https://github.com/opentracing/api-golang/blob/master/opentracing/standardtracer/standardimpl.go#L16) takes a separate `Recorder` and `TraceContextSource`.
1) FWIW, the "leak" of `NewRootTraceContext()` was deliberate, but I agree it doesn't need to be coupled in that way. Still, `opentracing` implementations will need to handle `NewRootTraceContext()` – it's not something that `standardtracer` can generalize about (or at least not in my opinion).

Speaking of package layout changes, I have some regrets about the naming of `standardtracer` and the ["default" tracer](https://github.com/opentracing/api-golang/blob/master/opentracing/defaulttracer.go#L13). Maybe the latter should be called the "global" tracer or "singleton" tracer or something?

If this is too annoying to discuss over github, I'm happy to hop on the phone or hangout/etc.

Thanks.

**Comment by bensigelman** [comment]
Re `NewChild`, I can see what you're saying and went back and forth about it. I liked `TraceContext.NewChild` more than `TraceContextSource.NewChildContext(parentCtx TraceContext, ...)` because it eliminates any question about whether `parentCtx` is the same type of `TraceContext` that the `TraceContextSource` creates. But I don't feel strongly about this and certainly understand the advantages of the approach you suggest.

One priority for me was making sure that *consumers* of the `opentracing` API/APIs are confused as little as possible. They will probably/hopefully not have to call `TraceContext.NewChild` very much to begin with, so that isn't a major concern here. But there were similar issues with the `Span` API where I decided to do the thing that I thought would be clearest from a `godocs` standpoint.

**Comment by yurishkuro** [comment]
The `Recorder` may also be part of `standard` package, along with `Raw`, because it's not exposed to client code via construction API.

I agree immutable things are nice, but I think your standard implementation keeps updating the underlying Raw Span.

**Comment by bensigelman** [comment]
Re: immutability, my point was that the consumer of `RawSpan`/`RawLog` can think of them as immutable. If we have performance issues in the future, maybe they even become lock-free when they make the transition, who knows.

Re: `Recorder`, yes, we could move it to the `standard` package from a deps standpoint. I was going to say that we'd have to move the noop `Tracer` impl in order to avoid a dependency cycle, but it turns out that the `noopRecorder` is no longer used. So I will send a PR to move this stuff around.

**Comment by adriancole** [comment]
drive-by commentary.. I'll probably refine this when digging into the java code

On `standardtracer` or `std` feels weird at least in java, particularly as a package. If the goal is to highlight that the type represents one of static singleton scope, I might call it default, system or platform, and not make a new package out of it.

**Comment by bensigelman** [comment]
@adriancole: `standardtracer` is not a singleton, it's just a stock `Tracer` implementation given a tracing-impl-provided `TraceContextSource` and `Recorder`. The idea is that a particularly odd/ambitious tracing impl could handle all of the `Tracer` interface, but most of them only need to bother with the `TraceContextSource` and `Recorder`.

This is not to suggest we have chosen the optimal name. :)  But maybe that helps in a collective effort to locate a better one.

**Comment by adriancole** [comment]
Thx I'll refrain on suggesting more until I play with it!

**Comment by peterbourgon** [comment]
Note from the peanut gallery: in certain circumstances it's okay for `github.com/user/repo/subpkg` to have a package name that isn't necessarily `subpkg`. See e.g. [github.com/tsenart/vegeta/lib](https://github.com/tsenart/vegeta/blob/master/lib), which imports as `vegeta`.

**Comment by bensigelman** [comment]
@peterbourgon nice to see you here :)

That is indeed what we've done... this issue is showing its age:

https://github.com/opentracing/opentracing-go/blob/master/tracer.go#L1

**Comment by bensigelman** [comment]
speaking of which: @yurishkuro should we close this for now?

**Comment by yurishkuro** [comment]
+1
