### ISSUE TITLE
OpenTracing doesn't have any API to get the ID of the trace back

### ISSUE THREAD

**Issue by PSG-Luna** [opentracing/opentracing-go#81]
the opentracing API should provide a `GetID()` or `GetCorrelationID()` function that returns the ID of the current trace. This is useful when logging errors to a seperate avenue, so that the ID can be put in the logs and be used to get trace information for an error.

**Comment by bensigelman** [comment]
OpenTracing (deliberately) does not specify how Spans are identified in any particular implementation. E.g., one OpenTracing implementation may choose to use an int64 for a SpanId and pair it with an int64 TraceId. Another may just have a string SpanId and nothing more. Others use existing context objects to assemble traces and have no guid of their own.

If you are comfortable making assumptions about your particular OpenTracing implementation, you can of course cast the `Span` interface to the appropriate type and grab an ID that way.

Another idea would be to add an explicit `String() string` method (including the span id, etc) to the Span implementation you're using, then just log it for debugging using `"%v"`, `fmt.Sprint(span)`, or similar.

I'm going to close this issue, but please reopen if the above doesn't make sense. Thanks.

**Comment by bsr203** [comment]
@bensigelman I too in need of getting `traceID` at creation so I can associate it with the request and later retrieve the trace for that request. type casting is an option but as I see it is not exported https://github.com/opentracing/basictracer-go/blob/master/span.go#L26 . Please let me know how to do this?

**Comment by yurishkuro** [comment]
@bsr203 you can do it like this: https://github.com/uber/jaeger-client-go/pull/41/files#diff-04c6e90faac2675aa89e2176d2eec7d8R135

**Comment by bsr203** [comment]
@yurishkuro thank you so much. Please let me know if I got it right. I could set an id to the context I pass to create the trace (debugID in this case), which can associate with traceID once the span is finished.

**Comment by bsr203** [comment]
@yurishkuro a quick qn.

this didn't work
```
	span, c := opentracing.StartSpanFromContext("HTTP", opentracing.Tag{Key: "debugID", Value: debugID})
	defer span.Finish()
```

but this does, as in your implementation,

```
    span, c := ctx.NewSpan("HTTP")
	defer span.Finish()
	span.SetTag("debugID", debugID)
```
didn't look at the implementation, but is `opentracing.Tag` not to set initial tags?

**Comment by eric-am** [comment]
I still have this complaint.  The reasons for wanting to be able to access the traceID (or spanID) remain the same as they did two years ago: I want to be able to stream them out in other logs and use them as correlation IDs, since... that's what they are.

> If you are comfortable making assumptions about your particular OpenTracing implementation, you can of course cast the Span interface to the appropriate type and grab an ID that way.

I'd be perfectly comfortable with this, both as a rebuttal and as an escape valve, except in practice, it still doesn't work.  To explain by example, here's why:

```go
	switch sctx := span.Context().(type) {
	case jaeger.SpanContext:
		correlationID = sctx.String()
	case opentracing.noopSpanContext: // DOES NOT COMPILE
		// something else
	default:
		panic("you switched ot libraries? o.o")
	}
```

Since `opentracing.noopSpanContext` shows up in normal usage -- regardless of which implementation you're using otherwise -- and you can't reference an unexported type like this... I'm at a loss for any way to write this code safely.  Instead, the nearest I can come up with is:

```go
	// This prints a reasonable thing in the case of jaeger,
	// and prints "{}" in the case of ot.noopSpanContext.
	// This is hacky, but we can't do a type-switch to detect
	// the unexported type in the no-op path, so, here we are.
	correlationID = fmt.Sprintf("%s", span.Context())
```

A `String() string` function on the SpanContext does *happen* to do the right thing, as illustrated in this second code block... but:
- it's still awfully janky looking; 
- worse, it's hard to access performantly since it's not in any of the core interfaces (hence necessitating the (slow|ugly|reflective) `Sprintf` hack);
- and *worst*, there's no standard for which object should even have the `String() string` -- the Span, or the SpanContext?  Span is suggested above; SpanContext is what I'm seeing would work on the libraries I'm handling today :/ -- and with no guidance or recommendations about how those should be implemented or on placeholders when they aren't, it's... Ehm.

I understand the deliberateness of not over-standardizing span identifiers.  But it's pretty darn rough out there without even a hint of an interface, nor defaults, nor guidance on this.  A little specification could go a long way.

**Comment by dkuebric** [comment]
Agreed this is a common request.  Another alternative within current API would be based on using `inject` to serialize the ID: http://opentracing.io/documentation/pages/api/cross-process-tracing.html

**Comment by eric-am** [comment]
Another member of my team is doing that trick on the JS side, yeah.

It works, but the fact that this is A) common and B) cross-language (...!!!!) seems to me to sort of make a farce of the idea that the IDs don't have a serializability mechanism that we can admit to.

**Comment by bhs** [comment]
This issue came up on the OTSC call this AM... general consensus was to move https://github.com/opentracing/specification/blob/master/rfc/trace_identifiers.md forward beginning on Monday.

There are a few subtleties regarding naming collisions with various Tracer impls, etc, but this will move forward soon.
